import type { Section } from "../schema";

export const homeSections: Section[] = [{
  type: "home_studio",
  props: {
    heroEyebrow: "Profile Landscapes · Sydney · Est. 1999",
    heroTitle: "We shape",
    heroItalic: "living places.",
    heroBody: "Landscape design, construction, horticulture and long-term care—delivered by one Sydney team from first sketch to established landscape.",
    heroImage: "/assets/projects/kinghorn-cancer-centre-restored.webp",
    heroImageAlt: "Timber seating and established courtyard planting at The Kinghorn Cancer Centre in Darlinghurst",
    heroNote: "Contractor / nursery / design studio",
    heroPrimary: { label: "Explore selected work ↗", href: "/projects" },
    heroSecondary: { label: "Invite us to tender", href: "/quote" },
    stats: [
      { value: "27", label: "Years shaping Sydney" },
      { value: "$11M", label: "Largest delivered package" },
      { value: "4,800+", label: "Plants across nursery stock" },
      { value: "682", label: "Published plant profiles" },
    ],
    introEyebrow: "A complete landscape practice",
    introTitle: "One team.",
    introItalic: "The whole landscape.",
    introBody: "The decisions that make landscapes succeed are connected. Our designers understand construction. Our crews understand planting. Our nursery understands what will establish—and our maintenance team stays with it as the landscape matures.",
    practices: [
      { number: "01", title: "Construct", body: "Commercial landscape construction, public realm, structures, irrigation, civil interfaces and detailed soft works.", href: "/services", label: "Construction capability ↗", icon: "/themes/profile-landscapes/home/practice-construct.webp", iconAlt: "White clay model of landscape construction and retaining walls" },
      { number: "02", title: "Design", body: "Site-led concepts, planting strategy, documentation and visualisation grounded in buildability.", href: "/landscape-design", label: "Enter the design studio ↗", icon: "/themes/profile-landscapes/home/practice-design.webp", iconAlt: "White clay landscape design model with contours and plans" },
      { number: "03", title: "Grow", body: "Retail and trade plant supply from our Petersham nursery, linked to real specifications and current stock.", href: "/plants", label: "Browse nursery stock ↗", icon: "/themes/profile-landscapes/home/practice-grow.webp", iconAlt: "White clay nursery plants in ceramic pots" },
      { number: "04", title: "Maintain", body: "Establishment, horticultural care and practical knowledge that protects the design intent after handover.", href: "/resources", label: "Open the field guides ↗", icon: "/themes/profile-landscapes/home/practice-maintain.webp", iconAlt: "White clay garden maintenance tools and young native plant" },
    ],
    workEyebrow: "Selected landscapes",
    workTitle: "Built for now.",
    workItalic: "Planted for what comes next.",
    workBody: "Healthcare, residential, education, hospitality and public landscapes across Sydney—each shaped by its site, brief and the people who will use it.",
    workCta: { label: "View the complete portfolio ↗", href: "/projects" },
    capabilityEyebrow: "Ideas made buildable",
    capabilityTitle: "Design intelligence, construction reality.",
    capabilityBody: "Good landscape design survives contact with programme, budget, structure, services and maintenance. Keeping design, estimating, procurement and delivery close gives every decision a clear path from drawing to site.",
    capabilityImage: "/assets/projects/trio-camperdown-pool-restored-v2.webp",
    capabilityImageAlt: "Completed pool terrace and landscape at Trio Apartments in Camperdown",
    capabilityGraphic: "/themes/profile-landscapes/home/practice-design.webp",
    capabilityGraphicAlt: "White clay landscape design model",
    capabilityCta: { label: "See how the practice works ↗", href: "/capability" },
    nurseryEyebrow: "The Petersham nursery",
    nurseryTitle: "Plants we know.",
    nurseryItalic: "Stock you can source.",
    nurseryBody: "Our live nursery is connected to the same plant knowledge used by the design and construction teams. Compare species, confirm care requirements, check available sizes and build a project schedule as you browse.",
    nurseryCta: { label: "Browse live nursery ↗", href: "/plants" },
    nurserySecondary: { label: "Open trade pricelist", href: "/plants/pricelist" },
    knowledgeEyebrow: "A useful landscape library",
    knowledgeTitle: "Specify with confidence.",
    knowledgeItalic: "Care with context.",
    knowledgeBody: "The encyclopedia brings botanical information, Sydney council guidance and nursery availability together. Illustrated field guides turn that reference into practical maintenance advice.",
    knowledgeLinks: [
      { title: "Plant encyclopedia", body: "Search botanical profiles, site conditions, care notes and local authority guidance.", href: "/encyclopedia", label: "Explore 683 profiles ↗" },
      { title: "Illustrated care guides", body: "Step-by-step help for watering, pruning, soil, pests and establishment.", href: "/resources", label: "Read the guides ↗" },
      { title: "Nursery availability", body: "Move from research to current sizes, prices and a shareable plant schedule.", href: "/plants", label: "Check live stock ↗" },
      { title: "Landscape design studio", body: "Turn a site, brief and planting direction into a coordinated landscape proposal.", href: "/landscape-design", label: "Start a design brief ↗" },
    ],
    tenderEyebrow: "Have a site, scope or tender?",
    tenderTitle: "Bring us in",
    tenderItalic: "while decisions still matter.",
    tenderBody: "Send the brief, drawings and programme. We can review the package, identify the right delivery pathway and tell you quickly what we need next.",
    tenderCta: { label: "Start a project enquiry ↗", href: "/quote" },
    tenderEmail: "carlo@profilelandscapes.com.au",
  },
}];
